Update to repo-config 0.4.0
frequenz-floss/frequenz-channels-python pull request #142
Opened 2023-07-20 08:59 UTC by Marenz

2023-07-27 10:29 UTC, llucax reviewed
Except for the copyright year updates, LGTM.

2023-07-27 10:29 UTC, llucax commented on LICENSE
> +Copyright © 2023 Frequenz Energy-as-a-Service GmbH
This shouldn't be updated.

2023-07-27 10:29 UTC, llucax commented on mkdocs.yml
> +copyright: "Copyright © 2023 Frequenz Energy-as-a-Service GmbH"
Nor this.

2023-07-27 10:29 UTC, llucax commented on pyproject.toml
> +# Copyright © 2023 Frequenz Energy-as-a-Service GmbH
Or this :D

2023-07-27 10:29 UTC, llucax commented
Please also remember to set the milestone to the PR (I already did it).

2023-07-27 10:42 UTC, Marenz commented
updated

2023-08-02 08:03 UTC, llucax requested changes
The year change is still there everywhere, maybe you forgot to push?

2023-08-02 08:32 UTC, Marenz commented
hu? You can see my force-push removed it here? https://github.com/frequenz-floss/frequenz-channels-python/compare/1787c949724100c0fd9f652b3f70e287b6c45448..eead2f927b665598242cb57a0520f00ac338d29f

2023-08-02 08:32 UTC, Marenz commented
And I don't see it in the files-changed tab either...

2023-08-02 12:15 UTC, llucax approved these changes
Now it looks fine. Maybe it was a cache issue on my side?

2023-08-02 13:32 UTC, merged