Add stop method for MergeNamed and Merge channels.
frequenz-floss/frequenz-channels-python pull request #68
Opened 2023-01-26 13:33 UTC by ela-kotulska-frequenz

Both channels stores async tasks that listen on the receivers. If they are removed without stopping the receivers tasks, then user gets error: Task was destroyed but it is pending!

`stop` method should be called when channel is no longer needed. Destructor can't be async, so we do that with extra method `stop`.

Signed-off-by: ela-kotulska-frequenz <elzbieta.kotulska@frequenz.com>

2023-01-26 14:20 UTC, mathias-baumann-frequenz requested changes
Should this be mentioned in the release notes?

2023-01-26 14:20 UTC, mathias-baumann-frequenz commented on src/frequenz/channels/util/_merge.py
> +        When Merge is no longer needed, then it should be stopped using
```suggestion
        When `merge` is no longer needed it should be stopped using
```

2023-01-26 14:20 UTC, mathias-baumann-frequenz commented on src/frequenz/channels/util/_merge_named.py
> +    When MergeNamed is no longer needed, then it should be stopped using
```suggestion
    When `MergeNamed` is no longer needed it should be stopped using the
```

2023-01-26 14:20 UTC, mathias-baumann-frequenz commented on src/frequenz/channels/util/_merge_named.py
> +    `self.stop()` method. This would cleanup any internal pending async tasks.
```suggestion
    `self.stop()` method. This will cleanup any internal pending async tasks.
```

2023-01-26 15:48 UTC, ela-kotulska-frequenz commented on src/frequenz/channels/util/_merge_named.py
> +    `self.stop()` method. This would cleanup any internal pending async tasks.
Thanks! Changed.

2023-01-26 15:48 UTC, ela-kotulska-frequenz commented on src/frequenz/channels/util/_merge_named.py
> +    When MergeNamed is no longer needed, then it should be stopped using
Thanks! Changed.

2023-01-26 15:48 UTC, ela-kotulska-frequenz commented on src/frequenz/channels/util/_merge.py
> +        When Merge is no longer needed, then it should be stopped using
Thanks! Changed.

2023-01-26 16:05 UTC, shsms commented on src/frequenz/channels/util/_merge.py
> +        When `merge` is no longer needed, then it should be stopped using
``` suggestion
        When `Merge` is no longer needed, it should be stopped using
```

2023-01-26 16:09 UTC, sahas-subramanian-frequenz approved these changes

2023-01-27 14:17 UTC, mathias-baumann-frequenz approved these changes

2023-01-27 14:19 UTC, merged